# Generated by Django 5.0.4 on 2024-04-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='media/')),
                ('brand_name', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
                ('discount_deal', models.CharField(choices=[('New Arrival', 'New Arrival'), ('Hot Deal', 'Hot Deal')], max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
